language: ruby
rvm:
  - 2.0.0
before_install:
  - sudo apt-get install -qq libclamav libclamav-dev
before_script:
  - "cp config/database.yml.travis config/database.yml"
services:
  - redis-server
  - clamav
script:
  - "bundle exec rake db:migrate spec"
notifications:
  irc: "irc.freenode.org#scholarsphere"
