language: ruby
rvm:
  - 2.0.0
before_install:
  - sudo apt-get install -qq clamav-daemon libclamav-dev
before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "cp config/redis.yml.sample config/redis.yml"
services:
  - redis-server
script:
  - "bundle exec rake db:migrate spec"
notifications:
  irc: "irc.freenode.org#scholarsphere"
